/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const stepperCustomDot: string;
const activeStepperCustomDot: string;
const completedStepperCustomDot: string;
const errorColor: string;

export {
  stepperCustomDot,
  activeStepperCustomDot,
  completedStepperCustomDot,
  errorColor,
};

export default {
  stepperCustomDot,
  activeStepperCustomDot,
  completedStepperCustomDot,
  errorColor,
};
