/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const root: string;
const li: string;

export { root, li };

export default {
  root,
  li,
};
