// Generated by Wrangler by running `wrangler types`

interface Env {
	LOG_LEVEL: "INFO"
	API_BASE_URL: "https://api.yeetunion.com"
	APP_BASE_URL: "https://app.yeetunion.com"
	HYPERDRIVE: Hyperdrive
	SYNC_TRANSACTIONS_WORKFLOW: Workflow
}
