name = "ye-api"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]


[observability]
enabled = true

[placement]
mode = "smart"

[env.production.vars]
API_BASE_URL = "https://api.yeetunion.com"
APP_BASE_URL = "https://app.yeetunion.com"


[triggers]
crons = ["*/10 * * * *"]

[[workflows]]
name = "workflow-transactions-sync"
binding = "SYNC_TRANSACTIONS_WORKFLOW"
class_name = "SyncTransactionsWorkflow"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "20471f3545bc4210bbee3142f31367ec"
localConnectionString = "postgres://postgres:password@127.0.0.1:5455/postgres?sslmode=disable"

[vars]
LOG_LEVEL = "INFO"
